import {
  bootstrapCheckCircleFill,
  bootstrapChevronDoubleLeft,
  bootstrapChevronDoubleRight,
  bootstrapChevronDown,
  bootstrapChevronLeft,
  bootstrapChevronRight,
  bootstrapChevronUp,
  bootstrapCode,
  bootstrapDownload,
  bootstrapEye,
  bootstrapFileCode,
  bootstrapFileEarmarkCode,
  bootstrapFileEarmarkPdfFill,
  bootstrapFileText,
  bootstrapGithub,
  bootstrapList,
  bootstrapPlusCircleFill,
  bootstrapPrinter,
  bootstrapSearch,
  bootstrapTrash,
  bootstrapTrashFill,
  bootstrapX,
} from '@ng-icons/bootstrap-icons';
import { provideIcons } from '@ng-icons/core';

export const provideAppIcon = () =>
  provideIcons({
    bootstrapGithub,
    bootstrapList,
    bootstrapX,
    bootstrapTrashFill,
    bootstrapTrash,
    bootstrapPlusCircleFill,
    bootstrapChevronUp,
    bootstrapChevronDown,
    bootstrapCheckCircleFill,
    bootstrapChevronRight,
    bootstrapChevronLeft,
    bootstrapPrinter,
    bootstrapFileEarmarkPdfFill,
    bootstrapFileEarmarkCode,
    bootstrapCode,
    bootstrapFileCode,
    bootstrapFileText,
    bootstrapSearch,
    bootstrapChevronDoubleLeft,
    bootstrapChevronDoubleRight,
    bootstrapDownload,
    bootstrapEye,
     
  });
